FROM node:22-bookworm-slim AS build
LABEL maintainer="Enrique Faz Dionisio <enrique71296@gmail.com>"
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG BUILD_CONFIG=production
ENV NODE_ENV=production
RUN npx ng build --configuration=$BUILD_CONFIG && rm -rf node_modules .angular

FROM nginx:bookworm
LABEL maintainer="Enrique Faz Dionisio <enrique71296@gmail.com>"
ENV NGINX_PORT=80
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/dnd-board-front/browser /usr/share/nginx/html
VOLUME ["/var/log/nginx"]
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
